baseURL = 'https://queryella.de'
title = 'Queryella'

defaultContentLanguage = "en"
languageCode = "en-us"

rssLimit  = 300
copyright = "Some rights reserved. Unless otherwise noted, content on this page is under a Creative Commons license."

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = true
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = true
disableLanguages = ['de']


pluralizeListTitles = false
paginate = 6

[build]
  writeStats = true
  
[permalinks]
  blog = "/blog/:filename/"
  jobs = "/jobs/:filename/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  author   = "authors"
  department   = "departments"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformBlog   = "2 January 2006"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

# Metadata mostly used in document's head
  description = "In-depth code analysis for your security & privacy. Queryella ermöglicht die tiefgehende Überprüfung von mobilen Apps auf Sicherheitslücken und ..."
  keywords = "code, analysis, security, apps, queryella"
  images = ["img/default.jpg"]

# Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

# Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  justifyContent = false
  contentTypeName = "blog"
 

# Colors for favicons
  [params.favicon.color]
    mask = ""
    msapplication = ""

# Social icons
  
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/queryella"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/company/queryella/"

# Menus - English
[languages]
  [languages.en]
    languageName = "English"
    subtitle  = ""
    contentDir   = "content/en"
    weight    = 1
    copyright = 'Some rights reserved. Unless otherwise noted, content on this page is under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener" title="License"> Creative Commons license</a>.'
  
  
  # Main navigation Menu
  [[languages.en.menu.main]]
    identifier = "solutions"
    name       = "Solutions"
    url        = "/solutions/"
    weight     = "1"
    
  [[languages.en.menu.main]]
    identifier = "publications"
    name       = "Publications"
    url        = "/publications/"
    weight     = "2"

  [[languages.en.menu.main]]
    identifier = "company"
    name       = "Company"
    weight     = "3"

  [[languages.en.menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    parent     = "company"
    weight     = "1"

  [[languages.en.menu.main]]
    identifier = "jobs"
    name       = "Jobs"
    url        = "/jobs/"
    parent     = "company"
    weight     = "2"

  [[languages.en.menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = "4"




  # Menus on footer / First Vertical Menu
  [[languages.en.menu.footer1]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = "1"
  
  [[languages.en.menu.footer1]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog"
    weight     = "2"

  [[languages.en.menu.footer1]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = "3"
    
  [[languages.en.menu.footer1]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact"
    weight     = "4"

  # Menus on footer / Second Vertical Menu

  [[languages.en.menu.footer2]]
    identifier = "solutions"
    name       = "Solutions"
    url        = "/solutions"
    weight     = "1"
  
  [[languages.en.menu.footer2]]
    identifier = "demo"
    name       = "Request a Demo"
    url        = "/request-a-demo"
    weight     = "2"

  [[languages.en.menu.footer2]]
    identifier = "publications"
    name       = "Publications"
    url        = "/publications"
    weight     = "3"

  # Menus on footer / Horizontal Menu

    [[languages.en.menu.footer3]]
    identifier = "imprint"
    name       = "Imprint"
    url        = "/imprint"
    weight     = "1"
  
  [[languages.en.menu.footer3]]
    identifier = "privacy-policy"
    name       = "Privacy Policy"
    url        = "/privacy-policy"
    weight     = "2"

  [[languages.en.menu.footer3]]
    identifier = "terms-of-service"
    name       = "Terms of Service"
    url        = "/terms-of-service"
    weight     = "3"


# Menus - German

  [languages.de]
    languageName = "Deutsch"
    subtitle  = ""
    contentDir   = "content/de"
    weight    = 2
    copyright = 'Some rights reserved. Unless otherwise noted, content on this page is under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener" title="License"> Creative Commons license</a>.'
  
  # Main navigation Menu

  [[languages.de.menu.main]]
    identifier = "solutions"
    name       = "Solutions"
    url        = "/solutions/"
    weight     = "1"

  [[languages.de.menu.main]]
    identifier = "publications"
    name       = "Publications"
    url        = "/publications/"
    weight     = "2"

  [[languages.de.menu.main]]
    identifier = "company"
    name       = "Company"
    weight     = "3"

  [[languages.de.menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    parent     = "company"
    weight     = "1"

  [[languages.de.menu.main]]
    identifier = "jobs"
    name       = "Jobs"
    url        = "/jobs/"
    parent     = "company"
    weight     = "2"

  [[languages.de.menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = "3"

  
  # Menus on footer / First Vertical Menu
  [[languages.de.menu.footer1]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = "1"
  
  [[languages.de.menu.footer1]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog"
    weight     = "2"

  [[languages.de.menu.footer1]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = "3"
    
  [[languages.de.menu.footer1]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact"
    weight     = "4"

  # Menus on footer / Second Vertical Menu

  [[languages.de.menu.footer2]]
    identifier = "solutions"
    name       = "Solutions"
    url        = "/solutions"
    weight     = "1"
  
  [[languages.de.menu.footer2]]
    identifier = "demo"
    name       = "Request a Demo"
    url        = "/request-a-demo"
    weight     = "2"

  [[languages.de.menu.footer2]]
    identifier = "publications"
    name       = "Publications"
    url        = "/publications"
    weight     = "3"

  # Menus on footer / Horizontal Menu

    [[languages.de.menu.footer3]]
    identifier = "imprint"
    name       = "Impressum"
    url        = "/imprint"
    weight     = "1"
  
  [[languages.de.menu.footer3]]
    identifier = "privacy-policy"
    name       = "Privacy Policy"
    url        = "/privacy-policy"
    weight     = "2"

  [[languages.de.menu.footer3]]
    identifier = "terms-of-service"
    name       = "Terms of Service"
    url        = "/terms-of-service"
    weight     = "3"


[privacy]
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
