name: Hugo

on:
  push:
    branches: [ main ]

jobs:
  build:

    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
         hugo-version: latest
         extended: true
         
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
          node-version: '16'
          cache: 'npm'
          # The action defaults to search for the dependency file (package-lock.json,
          # npm-shrinkwrap.json or yarn.lock) in the repository root, and uses its
          # hash as a part of the cache key.
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
          cache-dependency-path: '**/package-lock.json'
          
    - name: Build
      run: hugo --minify
    
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -rvzh --delete
        path: ./public/
        remote_path: web
        remote_host: ${{ secrets.DEPLOY_HOST }}        
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}    
