name: Hugo

on:
  push:
    branches: [ main ]

jobs:
  build:

    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
         hugo-version: latest
         extended: true

    - name: Build
      run: hugo --minify

    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -rvzh --delete
        path: ./public/
        remote_path: web
        remote_host: ${{ secrets.DEPLOY_HOST }}        
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}    
